---
title: "babiesByTimeOfDay"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r}

require(reshape)
require(ggplot2)
require(tidyr)

df <- read.csv('allBirths.csv', header = TRUE, as.is = TRUE)
df <- gather(df, dayOfWeek, value, Total:Saturday)

df <- na.omit(df)
df <- cast(df, DOB_WK ~ dayOfWeek, sum)

df <- gather(df, dayOfWeek, value, Friday:Wednesday)
df <- subset(df, DOB_WK != 'Not stated')
df <- subset(df, DOB_WK != 'Not on certificate')
df <- subset(df, DOB_WK != 'Total')

df$hourmin <- strptime(df$DOB_WK, '%H%M', tz="GMT")

df$dayOfWeek <- factor(df$dayOfWeek, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))

df <- subset(df, dayOfWeek != 'Total')
```

Let's start by just looking at the number of babies born by minute on Saturdays in 2014

```{r echo=FALSE, fig.width = 12, fig.height = 8}
ggplot(subset(df, dayOfWeek %in% c('Saturday')), aes(x=hourmin, y = value, color = dayOfWeek)) + geom_point(alpha = .3) + theme_bw() + scale_x_datetime(date_labels = "%H%M") + labs(x="Birth Hour/Minute", y="Number of Babies Born", title = "Babies born per Minute: Mondays and Saturdays in 2014") + coord_cartesian(ylim=c(0,1100)) + theme(axis.text=element_text(size=18), title=element_text(size=24)) + theme(panel.margin = unit(1.4, "lines"), strip.text.x = element_text(size = 20)) + scale_color_manual(values = c('steelblue'))+ theme(legend.position="none")
```

Let's look at Monday, as well as Saturday.

```{r echo=FALSE, fig.width = 12, fig.height = 8}
ggplot(subset(df, dayOfWeek %in% c('Saturday', 'Monday')), aes(x=hourmin, y = value, color = dayOfWeek)) + geom_point(alpha = .3) + theme_bw() + scale_x_datetime(date_labels = "%H%M") + labs(x="Birth Hour/Minute", y="Number of Babies Born", title = "Babies born per Minute: Mondays and Saturdays in 2014") + coord_cartesian(ylim=c(0,1100)) + theme(axis.text=element_text(size=18), title=element_text(size=24)) + theme(panel.margin = unit(1.4, "lines"), strip.text.x = element_text(size = 20)) + scale_color_manual(values = c('#8B4513', 'steelblue'))+ theme(legend.position="none")
```

And... all days of the week
```{r echo=FALSE, fig.width = 12, fig.height = 8}
ggplot(subset(df, dayOfWeek != 'Total'), aes(x=hourmin, y = value, color = dayOfWeek)) + geom_point(alpha = .3) + facet_wrap( ~ dayOfWeek, nrow = 2) + theme_bw() + scale_x_datetime(date_labels = "%H%M") + labs(x="Time of Day", y="Number of Babies", title = "Babies born in 2014, by minute and day of week") + coord_cartesian(ylim=c(0,1100)) + theme(axis.text=element_text(size=18), title=element_text(size=24)) + theme(panel.margin = unit(1.4, "lines"), strip.text.x = element_text(size = 20)) + scale_color_manual(values = c('#8B4513','#8B4513','#8B4513','#8B4513','#8B4513', 'steelblue','steelblue'))+ theme(legend.position="none")
```

